###############################################################################
# This is a Donghyun's configuration.

version: 0.92

# history
# 0.91 - add num_inputs, use 2 for num_outputs

######################################################
## neural network 

# network definition
network_type: 77       # refer to neural_net/const.py
gpus: 1

weight_load: False

vae: True
latent: False
style_train: False
style_run: False
lstm: False
lstm_timestep: 5
lstm_dataterm: 1
data_timegap: 3       # seconds
lstm_lr: 0.0001        # 

cnn_lr:  0.0001          # default of Adam is 0.001

decay: 0.0000000001        #lstm = 1e-9, cnn = 1e-7 0.00000001
# normalize data
data_split: True
normalize_data: False
samples_per_bin: 4000
# training 
# data_shuffle: True
validation_rate: 0.3
num_epochs: 5000
batch_size: 32
num_inputs: 1     # input: image, velocity
num_outputs: 1    # output: steering_angle, throttle, brake
only_thr_brk: False
early_stopping_patience: 3000
# tensorboard log dir
tensorboard_log_dir: logs/scalars/

# data augmentation
data_aug_flip: False
data_aug_bright: False
data_aug_shift: False
# input image size to the neural network
input_image_width : 160 #160 #270 # 160 # 512
input_image_height: 160 #160 #90  # 160 # 96
input_image_depth : 3

# steering data preprocessing
# - steering angle adjustment
steering_angle_scale: 5.0
throttle_scale: 5.0
brake_scale: 5.0
# - steering wheel jitter tolerance
steering_angle_jitter_tolerance: 0.01
